# Nome da aplicação
spring.application.name=Vaidmassas

# Configurações da Conexão MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/vaidmassas?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=dev2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate/JPA
# update: Cria as tabelas automaticamente se não existirem ou altera se você mudar o Model
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect